export const course = {
  slug: "remote-medical-careers",
  title: "AfyaDesk Remote Medical Careers Course",
  subtitle: "Become Remote-Ready for Global Healthcare Opportunities",
  by: "By AfyaDesk",
  price: 1500,
  currency: "KSh",
  duration: "8–10 weeks • ~60 hours • Self-paced + live Q&A + simulations",
  description:
    "Designed for healthcare professionals and medical support applicants who want to transition from traditional environments into remote medical, healthcare administration, telehealth, medical VA and healthcare support roles. Combines healthcare knowledge with digital, communication, administrative and professional skills for remote work.",
  coverImage: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=1200&q=80",
  rating: 4.8,
  students: 1200,
  promise: "Don’t just apply for remote healthcare jobs. Become the candidate employers are looking for.",
  disclaimer:
    "AfyaDesk does not guarantee employment, interviews, clients or income after completion. The course improves career readiness and practical skills; opportunities depend on qualifications, performance, experience, employer requirements and available vacancies. Clinical responsibilities remain subject to licensing and employer policies.",

  objectives: [
    "Understand the remote healthcare job market",
    "Identify suitable remote medical roles",
    "Create a professional remote healthcare CV",
    "Build an attractive LinkedIn profile",
    "Write effective applications and cover letters",
    "Prepare for remote medical interviews",
    "Communicate professionally with international patients and teams",
    "Use common healthcare and remote-work technologies",
    "Understand medical virtual assistant workflows",
    "Perform common healthcare administrative tasks",
    "Understand confidentiality and healthcare data protection",
    "Work effectively across different time zones",
    "Build a professional remote work environment",
    "Apply confidently for international remote healthcare opportunities",
  ],

  modules: [
    {
      n: "01",
      title: "Introduction to Remote Healthcare Careers",
      topics: [
        "What is remote healthcare?",
        "Growth of telehealth and healthcare outsourcing",
        "Remote healthcare vs traditional healthcare employment",
        "The global medical virtual assistant industry",
        "Healthcare jobs that can be performed remotely",
        "Kenyan healthcare professionals in the global remote workforce",
        "Understanding international employers",
        "Freelance vs contract vs full-time remote employment",
      ],
      roles: [
        "Medical Virtual Assistant",
        "Medical Administrative Assistant",
        "Medical Receptionist",
        "Telehealth Coordinator",
        "Patient Care Coordinator",
        "Medical Scheduler",
        "Medical Transcriptionist",
        "Medical Customer Support",
        "Medical Records Assistant",
        "Medical Billing Assistant",
        "Healthcare Data Entry Specialist",
        "Referral Coordinator",
        "Prior Authorization Assistant",
        "Remote Healthcare Support Specialist",
      ],
      assignment: "Identify 5 remote healthcare roles that match your education, experience and skills.",
    },
    {
      n: "02",
      title: "Becoming a Remote-Ready Healthcare Professional",
      topics: [
        "What remote employers look for",
        "Professionalism in remote work",
        "Reliability and accountability",
        "Time management",
        "Working independently",
        "Following Standard Operating Procedures",
        "Attention to detail",
        "Meeting deadlines",
        "Digital professionalism",
        "Problem-solving",
        "Working without constant supervision",
      ],
      mindset: {
        from: "I am waiting to be told what to do",
        to: "I understand the task, execute it correctly and communicate progress.",
      },
      assignment: "Complete a simulated remote healthcare workday.",
    },
    {
      n: "03",
      title: "Medical Virtual Assistant Fundamentals",
      topics: [
        "Role of a Medical Virtual Assistant",
        "Responsibilities and limitations",
        "Medical office workflows",
        "Patient communication",
        "Appointment scheduling",
        "Calendar management",
        "Patient follow-ups",
        "Referral coordination",
        "Administrative documentation",
        "Email management",
        "Telephone support",
        "Patient onboarding",
        "Healthcare customer service",
      ],
      simulations: [
        "Booking an appointment",
        "Rescheduling a patient",
        "Sending appointment reminders",
        "Handling a patient inquiry",
        "Escalating a clinical concern",
        "Following up with a patient",
        "Managing a doctor’s calendar",
      ],
    },
    {
      n: "04",
      title: "Medical Terminology & Documentation",
      topics: [
        "Common medical terminology",
        "Anatomy and physiology terminology",
        "Common abbreviations",
        "Common diseases and conditions",
        "Medication terminology",
        "Diagnostic terminology",
        "Clinical documentation",
        "SOAP notes",
        "Referral letters",
        "Discharge documentation",
        "Medical correspondence",
      ],
      principle: "A medical virtual assistant should understand medical terminology while recognizing the boundaries between administrative support and clinical decision-making.",
    },
    {
      n: "05",
      title: "Patient Communication & Customer Service",
      topics: [
        "Professional telephone communication",
        "Email etiquette",
        "Patient-centred communication",
        "Active listening",
        "Empathy",
        "Handling difficult patients",
        "Managing complaints",
        "Professional WhatsApp communication",
        "Written communication",
        "Cultural sensitivity",
        "Communicating with international patients",
      ],
      roleplays: [
        "An angry patient",
        "A patient requesting an urgent appointment",
        "A patient who missed an appointment",
        "A confused patient",
        "A patient asking a clinical question outside the assistant’s scope",
      ],
    },
    {
      n: "06",
      title: "Telehealth & Digital Health Workflows",
      topics: [
        "How telemedicine works",
        "Virtual consultations",
        "Patient onboarding",
        "Telehealth scheduling",
        "Digital patient communication",
        "Virtual consultation preparation",
        "Follow-up workflows",
        "Remote healthcare teams",
        "Electronic Medical Records",
        "Patient portals",
        "Digital healthcare documentation",
      ],
      assignment: "Create a complete workflow for a virtual patient appointment.",
    },
    {
      n: "07",
      title: "Electronic Medical Records & Healthcare Software",
      intro: "Introduction to the types of systems commonly used by remote healthcare teams:",
      topics: [
        "Electronic Medical Records",
        "Practice Management Systems",
        "Patient portals",
        "Scheduling platforms",
        "CRM systems",
        "Communication platforms",
        "Document management systems",
      ],
      skills: [
        "Searching patient records",
        "Updating administrative information",
        "Scheduling appointments",
        "Uploading documents",
        "Managing patient tasks",
        "Maintaining accurate records",
      ],
      note: "Students should understand that specific software varies by employer.",
    },
    {
      n: "08",
      title: "Medical Data, Confidentiality & Privacy",
      topics: [
        "Patient confidentiality",
        "Healthcare data protection",
        "Data minimization",
        "Access control",
        "Secure passwords",
        "Phishing awareness",
        "Social engineering",
        "Secure communication",
        "Device security",
        "Handling patient information",
        "Reporting security incidents",
      ],
      kenya: "Introduce the principles of the Kenya Data Protection Act, 2019 and the importance of protecting personal and health information. Also introduce international healthcare privacy requirements encountered with overseas organizations.",
      assignment: "Identify security and confidentiality risks in a simulated remote medical workplace.",
    },
    {
      n: "09",
      title: "Medical Administration",
      topics: [
        "Appointment management",
        "Patient registration",
        "Referral management",
        "Medical records administration",
        "Documentation",
        "Insurance administration",
        "Claims support",
        "Billing support",
        "Prior authorization concepts",
        "Follow-up systems",
        "Administrative reporting",
      ],
      exercises: ["Patient registration", "Referral tracking", "Appointment scheduling", "Insurance documentation", "Administrative follow-up"],
    },
    {
      n: "10",
      title: "Medical Transcription & Documentation",
      topics: [
        "Introduction to medical transcription",
        "Listening skills",
        "Medical terminology",
        "Formatting medical documents",
        "Accuracy",
        "Proofreading",
        "Common transcription mistakes",
        "AI-assisted transcription",
        "Human verification of AI-generated transcripts",
      ],
      assignment: "Transcribe and format a simulated medical consultation.",
    },
    {
      n: "11",
      title: "Remote Healthcare Technology",
      groups: [
        { label: "Communication", items: ["Email", "Microsoft Teams", "Zoom", "Slack"] },
        { label: "Productivity", items: ["Google Workspace", "Microsoft 365", "Calendar systems", "Task-management platforms"] },
        { label: "Healthcare", items: ["EMR/EHR systems", "Practice management platforms", "Patient portals", "Telehealth platforms"] },
        {
          label: "AI",
          items: [
            "Introduction to responsible use of AI for: drafting administrative communication, summarizing non-sensitive info, transcription assistance, task organization, research assistance, productivity",
          ],
          note: "Emphasize that sensitive patient information should not be entered into AI tools unless the employer has explicitly authorized the tool and appropriate privacy protections are in place.",
        },
      ],
    },
    {
      n: "12",
      title: "Professional English & International Communication",
      topics: [
        "Professional English",
        "Medical communication",
        "Email writing",
        "Telephone etiquette",
        "Clear written communication",
        "Understanding different accents",
        "Communicating with US/UK/Australian clients",
        "Professional vocabulary",
        "Avoiding slang",
        "Handling misunderstandings",
      ],
      assignment: "Write: a professional patient email, a doctor’s appointment confirmation, a follow-up message, a workplace escalation email.",
    },
    {
      n: "13",
      title: "Building Your Remote Career Profile",
      topics: [
        "Creating a remote-ready CV",
        "CV formatting",
        "Applicant Tracking Systems (ATS)",
        "Writing a strong professional summary",
        "Highlighting transferable skills",
        "Quantifying achievements",
        "LinkedIn optimization",
        "Professional profile photography",
        "LinkedIn headline",
        "LinkedIn About section",
        "Skills and certifications",
        "Building a professional digital footprint",
      ],
      framework: "Students create a CV specifically optimized for Remote Medical Assistant / Healthcare Support roles (AfyaDesk CV Framework).",
    },
    {
      n: "14",
      title: "Job Search & Application Strategy",
      topics: [
        "Where to find legitimate remote healthcare jobs",
        "Understanding job descriptions",
        "Matching your skills to requirements",
        "Keyword optimization",
        "ATS applications",
        "Tailoring your CV",
        "Writing cover letters",
        "Cold applications",
        "Recruiter outreach",
        "LinkedIn networking",
        "Remote healthcare communities",
        "Avoiding fake remote jobs and recruitment scams",
      ],
      formula: "Research → Match → Tailor → Apply → Follow Up → Interview → Improve",
      assignment: "Submit applications for 5 simulated remote healthcare positions.",
    },
    {
      n: "15",
      title: "Remote Medical Interview Mastery",
      topics: [
        "Video interview preparation",
        "Common remote interview questions",
        "Medical VA interview questions",
        "Behavioural interviews",
        "STAR method",
        "Handling scenario-based questions",
        "Discussing salary",
        "Demonstrating professionalism",
        "Explaining gaps in employment",
        'Answering "Why should we hire you?"',
        "Handling difficult patient scenarios",
      ],
      mock: "Each learner completes a simulated remote healthcare interview.",
    },
    {
      n: "16",
      title: "Remote Workplace Setup",
      topics: [
        "Reliable internet",
        "Backup connectivity",
        "Laptop/computer requirements",
        "Headsets",
        "Webcam",
        "Quiet workspace",
        "Power backup",
        "Professional background",
        "Data security",
        "Productivity tools",
      ],
      kenyaPlan: "Create a practical backup plan covering: Internet + Power + Device + Communication (Kenya-specific remote work planning).",
    },
    {
      n: "17",
      title: "Working Across Time Zones",
      topics: [
        "UTC",
        "East Africa Time",
        "UK time",
        "US time zones",
        "Australian time zones",
        "Daylight saving time",
        "Scheduling across countries",
        "Managing night shifts",
        "Calendar conversion",
      ],
      exercise: "Convert a patient’s appointment between: Kenya → UK → New York → California.",
    },
    {
      n: "18",
      title: "AI for the Modern Medical VA",
      topics: [
        "AI fundamentals",
        "AI-assisted productivity",
        "Prompt writing",
        "Email drafting",
        "Document summarization",
        "Administrative workflow automation",
        "AI transcription",
        "Research assistance",
        "Quality control",
        "AI limitations",
        "Patient privacy and responsible AI use",
      ],
      assignment: "Design an AI-assisted workflow that saves a healthcare practice administrative time while maintaining human review and confidentiality.",
    },
    {
      n: "19",
      title: "Freelancing & International Clients",
      topics: [
        "Freelance healthcare support",
        "Finding clients",
        "Proposals",
        "Client communication",
        "Contracts",
        "Invoicing",
        "Professional boundaries",
        "Building long-term client relationships",
        "Getting referrals",
        "Building a professional reputation",
      ],
    },
    {
      n: "20",
      title: "Career Readiness & AfyaDesk Talent Pool",
      intro: "The final module prepares qualified learners for potential opportunities through AfyaDesk.",
      assessments: [
        "CV assessment",
        "LinkedIn assessment",
        "Medical terminology test",
        "Communication assessment",
        "Medical VA practical assessment",
        "Computer skills assessment",
        "Remote-work readiness assessment",
        "Mock interview",
      ],
      note: "Successful learners can be considered for relevant AfyaDesk talent opportunities, subject to recruitment requirements and available positions. Course completion does not guarantee employment; selection depends on qualifications, performance, experience, client requirements and available opportunities.",
    },
  ],

  capstone: {
    title: "Final Capstone Project",
    scenario: "You have been hired as a Medical Virtual Assistant for a private medical practice. You must:",
    tasks: [
      "Manage a doctor’s calendar",
      "Schedule patient appointments",
      "Respond to patient emails",
      "Handle a cancellation",
      "Process a referral",
      "Update an administrative patient record",
      "Prepare a follow-up list",
      "Handle a difficult patient interaction",
      "Escalate a clinical issue appropriately",
      "Complete an end-of-day report",
    ],
    note: "This project tests whether the learner can actually perform the job — not just pass a theory exam.",
  },

  assessment: {
    continuous: { weight: "30%", items: ["Quizzes", "Assignments", "Communication exercises", "Practical tasks"] },
    practical: { weight: "30%", items: ["Medical VA simulations", "Patient communication", "Scheduling", "Documentation", "Technology tasks"] },
    exam: { weight: "15%", items: ["Medical terminology", "Healthcare administration", "Privacy", "Remote work", "Digital skills"] },
    capstone: { weight: "15%", label: "Complete simulated remote medical workflow." },
    mock: { weight: "10%", label: "Professional remote healthcare interview." },
  },

  completion: {
    title: "AfyaDesk Remote Medical Careers Certificate",
    areas: ["Remote Medical Support", "Medical Administration", "Medical Virtual Assistance", "Telehealth Support"],
    note: "Include a unique certificate number and verification page.",
  },

  specializations: [
    { code: "Track A", title: "Medical Virtual Assistant" },
    { code: "Track B", title: "Telehealth Coordinator" },
    { code: "Track C", title: "Medical Receptionist" },
    { code: "Track D", title: "Medical Transcription" },
    { code: "Track E", title: "Medical Billing & Claims Support" },
    { code: "Track F", title: "Patient Support Specialist" },
    { code: "Track G", title: "Healthcare Administrative Assistant" },
  ],

  pathway: ["Learn", "Practice", "Assess", "Certify", "Build Profile", "Apply", "Interview", "Work"],

  portalFeatures: [
    "View course progress",
    "Watch lessons",
    "Download resources",
    "Complete quizzes",
    "Submit assignments",
    "Take assessments",
    "View scores",
    "Book mock interviews",
    "Build their professional profile",
    "Upload their CV",
    "Track application readiness",
    "View certificate",
    "Access career resources",
  ],

  talentProfileFields: [
    "Professional name",
    "Professional summary",
    "Healthcare qualification",
    "Experience",
    "Skills",
    "Certifications",
    "Remote-work skills",
    "Medical specialties/experience",
    "Software skills",
    "English proficiency",
    "Availability",
    "Time-zone availability",
    "CV",
    "Assessment scores",
    "Certificate",
    "Interview status",
  ],

  benefits: [
    "Prioritised shortlisting — course graduates jump the queue",
    "Interview prep & mock calls with feedback",
    "Certificate you can attach to any AfyaDesk application",
    "Direct match to open roles upon completion",
    "Lifetime alumni community & refresher access",
  ],
  outcomes: [
    "Handle 30+ admin tasks confidently",
    "Pass AfyaDesk screening first attempt",
    "Communicate like a healthcare professional",
    "Work securely & compliantly from day one",
  ],
  faqs: [
    { q: "Is the course mandatory?", a: "No — you can apply without it. But graduates are prioritised for shortlisting because they’re proven ready. Highly recommended if you’re new to healthcare support." },
    { q: "How is the course fee paid?", a: "M-Pesa Paybill or bank transfer. After enrolment you’ll get Paybill + account reference. Enter M-Pesa code to verify. One-time fee, lifetime certificate — see current price on enroll page." },
    { q: "Will I get hired automatically?", a: "No guaranteed hiring — we prioritise graduates but still match based on client fit and openings. You’ll be first to be considered. Clinical responsibilities remain subject to licensing and employer policies." },
  ],
};
